### ISSUE TITLE
Setup-infrastructure failed

### ISSUE THREAD

**Issue by DennisDenuto** [pivotal-cf-experimental/bosh-bootloader#55] opened 2016-08-17 22:32 UTC
```
bbl --version
bbl 0.0.1
```
Ran:
`bbl     --state-dir bbl-infrastructure     --aws-access-key-id [REDACTED]     --aws-secret-access-key [REDACTED]     --aws-region us-east-1     unsupported-deploy-bosh-on-aws-for-concourse`

Cloudformation output:
```
2016-08-17	Status	Type	Logical ID	Status reason
14:59:17 UTC-0700	UPDATE_ROLLBACK_COMPLETE	AWS::CloudFormation::Stack	bbl-aws-hR3w8	
14:59:16 UTC-0700	DELETE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet4	
14:59:16 UTC-0700	DELETE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet1	
14:59:15 UTC-0700	DELETE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet2	
14:59:15 UTC-0700	DELETE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet3	
14:59:00 UTC-0700	DELETE_COMPLETE	AWS::EC2::RouteTable	LoadBalancerRouteTable	
14:59:00 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet4	
14:58:59 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet2	
14:58:59 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::RouteTable	LoadBalancerRouteTable	
14:58:59 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet1	
14:58:59 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet3	
14:58:57 UTC-0700	DELETE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet4RouteTableAssociation	
14:58:57 UTC-0700	DELETE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet2RouteTableAssociation	
14:58:57 UTC-0700	DELETE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet1RouteTableAssociation	
14:58:57 UTC-0700	DELETE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet3RouteTableAssociation	
14:58:56 UTC-0700	DELETE_COMPLETE	AWS::EC2::Route	LoadBalancerRoute	
14:58:46 UTC-0700	DELETE_COMPLETE	AWS::EC2::SecurityGroup	CFRouterSecurityGroup	
14:58:46 UTC-0700	DELETE_COMPLETE	AWS::EC2::SecurityGroup	CFSSHProxySecurityGroup	
14:58:45 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFRouterSecurityGroup	
14:58:45 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFSSHProxySecurityGroup	
14:58:42 UTC-0700	DELETE_COMPLETE	AWS::EC2::SecurityGroup	CFRouterInternalSecurityGroup	
14:58:42 UTC-0700	DELETE_COMPLETE	AWS::EC2::SecurityGroup	CFSSHProxyInternalSecurityGroup	
14:58:41 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet4RouteTableAssociation	
14:58:41 UTC-0700	DELETE_COMPLETE	AWS::ElasticLoadBalancing::LoadBalancer	CFSSHProxyLoadBalancer	
14:58:41 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet2RouteTableAssociation	
14:58:41 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet1RouteTableAssociation	
14:58:41 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFRouterInternalSecurityGroup	
14:58:41 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet3RouteTableAssociation	
14:58:41 UTC-0700	DELETE_COMPLETE	AWS::ElasticLoadBalancing::LoadBalancer	CFRouterLoadBalancer	
14:58:41 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::Route	LoadBalancerRoute	
14:58:40 UTC-0700	DELETE_IN_PROGRESS	AWS::ElasticLoadBalancing::LoadBalancer	CFSSHProxyLoadBalancer	
14:58:40 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFSSHProxyInternalSecurityGroup	
14:58:38 UTC-0700	UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	bbl-aws-hR3w8	
14:58:22 UTC-0700	UPDATE_ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	bbl-aws-hR3w8	The following resource(s) failed to create: [CFRouterLoadBalancer, CFSSHProxyInternalSecurityGroup, CFRouterInternalSecurityGroup, LoadBalancerSubnet3RouteTableAssociation, LoadBalancerSubnet1RouteTableAssociation, LoadBalancerSubnet2RouteTableAssociation, LoadBalancerSubnet4RouteTableAssociation].
14:58:20 UTC-0700	CREATE_FAILED	AWS::EC2::SecurityGroup	CFRouterInternalSecurityGroup	Resource creation cancelled
14:58:16 UTC-0700	CREATE_FAILED	AWS::EC2::SecurityGroup	CFSSHProxyInternalSecurityGroup	Resource creation cancelled
14:58:09 UTC-0700	CREATE_FAILED	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet1RouteTableAssociation	Resource creation cancelled
14:58:08 UTC-0700	CREATE_FAILED	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet2RouteTableAssociation	Resource creation cancelled
14:58:08 UTC-0700	CREATE_FAILED	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet3RouteTableAssociation	Resource creation cancelled
14:58:08 UTC-0700	CREATE_FAILED	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet4RouteTableAssociation	Resource creation cancelled
14:58:08 UTC-0700	CREATE_COMPLETE	AWS::ElasticLoadBalancing::LoadBalancer	CFSSHProxyLoadBalancer	
14:58:08 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet1RouteTableAssociation	Resource creation Initiated
14:58:07 UTC-0700	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancing::LoadBalancer	CFSSHProxyLoadBalancer	Resource creation Initiated
14:58:07 UTC-0700	CREATE_FAILED	AWS::ElasticLoadBalancing::LoadBalancer	CFRouterLoadBalancer	Server Certificate not found for the key: arn:aws:iam::126623727247:server-certificate/bbl-cert-dfb7b96b-111f-d16e-5854-9936e7153e8b
14:58:07 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet1RouteTableAssociation	
14:58:07 UTC-0700	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancing::LoadBalancer	CFRouterLoadBalancer	
14:58:06 UTC-0700	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancing::LoadBalancer	CFSSHProxyLoadBalancer	
14:58:05 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFRouterInternalSecurityGroup	
14:58:02 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet1	
14:58:01 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet4RouteTableAssociation	Resource creation Initiated
14:58:01 UTC-0700	CREATE_COMPLETE	AWS::EC2::Route	LoadBalancerRoute	
14:58:00 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet3RouteTableAssociation	Resource creation Initiated
14:58:00 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet4RouteTableAssociation	
14:58:00 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet2RouteTableAssociation	Resource creation Initiated
14:58:00 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFSSHProxyInternalSecurityGroup	
14:58:00 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroup	CFRouterSecurityGroup	
14:57:59 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet3RouteTableAssociation	
14:57:59 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	LoadBalancerSubnet2RouteTableAssociation	
14:57:58 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFRouterSecurityGroup	Resource creation Initiated
14:57:56 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroup	CFSSHProxySecurityGroup	
14:57:55 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet4	
14:57:55 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet3	
14:57:55 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet2	
14:57:54 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFSSHProxySecurityGroup	Resource creation Initiated
14:57:46 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet1	Resource creation Initiated
14:57:45 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet1	
14:57:45 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Route	LoadBalancerRoute	Resource creation Initiated
14:57:44 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Route	LoadBalancerRoute	
14:57:42 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFRouterSecurityGroup	
14:57:40 UTC-0700	CREATE_COMPLETE	AWS::EC2::RouteTable	LoadBalancerRouteTable	
14:57:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	LoadBalancerRouteTable	Resource creation Initiated
14:57:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet3	Resource creation Initiated
14:57:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	LoadBalancerRouteTable	
14:57:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet2	Resource creation Initiated
14:57:38 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet4	Resource creation Initiated
14:57:38 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet3	
14:57:38 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	CFSSHProxySecurityGroup	
14:57:38 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet2	
14:57:38 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	LoadBalancerSubnet4	
14:57:32 UTC-0700	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	bbl-aws-hR3w8	User Initiated
```

Prior events:
```
14:44:29 UTC-0700	CREATE_COMPLETE	AWS::CloudFormation::Stack	bbl-aws-hR3w8	
14:44:26 UTC-0700	CREATE_COMPLETE	AWS::EC2::EIP	NATEIP	
14:44:11 UTC-0700	CREATE_COMPLETE	AWS::EC2::Route	InternalRoute	
14:43:55 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Route	InternalRoute	Resource creation Initiated
14:43:55 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::EIP	NATEIP	Resource creation Initiated
14:43:55 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::EIP	NATEIP	
14:43:54 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Route	InternalRoute	
14:43:51 UTC-0700	CREATE_COMPLETE	AWS::EC2::Instance	NATInstance	
14:43:03 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Instance	NATInstance	Resource creation Initiated
14:43:03 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressUDPfromBOSH	
14:43:03 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressTCPfromBOSH	
14:43:02 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Instance	NATInstance	
14:43:02 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressUDPfromBOSH	Resource creation Initiated
14:43:02 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressTCPfromBOSH	Resource creation Initiated
14:43:02 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressUDPfromBOSH	
14:43:01 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressTCPfromBOSH	
14:42:58 UTC-0700	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet3RouteTableAssociation	
14:42:58 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroup	BOSHSecurityGroup	
14:42:58 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroup	NATSecurityGroup	
14:42:57 UTC-0700	CREATE_COMPLETE	AWS::EC2::EIP	BOSHEIP	
14:42:57 UTC-0700	CREATE_COMPLETE	AWS::EC2::Route	BOSHRoute	
14:42:56 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	NATSecurityGroup	Resource creation Initiated
14:42:56 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	BOSHSecurityGroup	Resource creation Initiated
14:42:55 UTC-0700	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet1RouteTableAssociation	
14:42:55 UTC-0700	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet2RouteTableAssociation	
14:42:55 UTC-0700	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet4RouteTableAssociation	
14:42:55 UTC-0700	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	BOSHSubnetRouteTableAssociation	
14:42:42 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressUDPfromSelf	
14:42:42 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::EIP	BOSHEIP	Resource creation Initiated
14:42:42 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet3RouteTableAssociation	Resource creation Initiated
14:42:41 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Route	BOSHRoute	Resource creation Initiated
14:42:41 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressTCPfromSelf	
14:42:41 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::EIP	BOSHEIP	
14:42:41 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet3RouteTableAssociation	
14:42:41 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressUDPfromSelf	Resource creation Initiated
14:42:41 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressUDPfromSelf	
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	NATSecurityGroup	
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Route	BOSHRoute	
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet2RouteTableAssociation	Resource creation Initiated
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressTCPfromSelf	Resource creation Initiated
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet4RouteTableAssociation	Resource creation Initiated
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet1RouteTableAssociation	Resource creation Initiated
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	BOSHSecurityGroup	
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	BOSHSubnetRouteTableAssociation	Resource creation Initiated
14:42:40 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroupIngress	InternalSecurityGroupIngressTCPfromSelf	
14:42:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet4RouteTableAssociation	
14:42:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet2RouteTableAssociation	
14:42:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	InternalSubnet1RouteTableAssociation	
14:42:39 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	BOSHSubnetRouteTableAssociation	
14:42:38 UTC-0700	CREATE_COMPLETE	AWS::IAM::AccessKey	BOSHUserAccessKey	
14:42:37 UTC-0700	CREATE_IN_PROGRESS	AWS::IAM::AccessKey	BOSHUserAccessKey	Resource creation Initiated
14:42:37 UTC-0700	CREATE_IN_PROGRESS	AWS::IAM::AccessKey	BOSHUserAccessKey	
14:42:37 UTC-0700	CREATE_COMPLETE	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	
14:42:36 UTC-0700	CREATE_COMPLETE	AWS::EC2::SecurityGroup	InternalSecurityGroup	
14:42:36 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	InternalSubnet3	
14:42:36 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	InternalSubnet2	
14:42:36 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	InternalSubnet4	
14:42:36 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	InternalSubnet1	
14:42:35 UTC-0700	CREATE_COMPLETE	AWS::EC2::Subnet	BOSHSubnet	
14:42:35 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	InternalSecurityGroup	Resource creation Initiated
14:42:34 UTC-0700	CREATE_COMPLETE	AWS::IAM::User	BOSHUser	
14:42:21 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	Resource creation Initiated
14:42:21 UTC-0700	CREATE_COMPLETE	AWS::EC2::RouteTable	InternalRouteTable	
14:42:20 UTC-0700	CREATE_COMPLETE	AWS::EC2::RouteTable	BOSHRouteTable	
14:42:20 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet2	Resource creation Initiated
14:42:20 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet3	Resource creation Initiated
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet4	Resource creation Initiated
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	InternalRouteTable	Resource creation Initiated
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet1	Resource creation Initiated
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	BOSHSubnet	Resource creation Initiated
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	BOSHRouteTable	Resource creation Initiated
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet2	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet3	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	InternalRouteTable	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	InternalSecurityGroup	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet1	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	BOSHRouteTable	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	InternalSubnet4	
14:42:19 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::Subnet	BOSHSubnet	
14:42:15 UTC-0700	CREATE_COMPLETE	AWS::EC2::VPC	VPC	
14:42:13 UTC-0700	CREATE_COMPLETE	AWS::EC2::InternetGateway	VPCGatewayInternetGateway	
14:41:58 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::VPC	VPC	Resource creation Initiated
14:41:57 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::InternetGateway	VPCGatewayInternetGateway	Resource creation Initiated
14:41:57 UTC-0700	CREATE_IN_PROGRESS	AWS::IAM::User	BOSHUser	Resource creation Initiated
14:41:57 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::VPC	VPC	
14:41:57 UTC-0700	CREATE_IN_PROGRESS	AWS::EC2::InternetGateway	VPCGatewayInternetGateway	
14:41:57 UTC-0700	CREATE_IN_PROGRESS	AWS::IAM::User	BOSHUser	
14:41:52 UTC-0700	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	bbl-aws-hR3w8	User Initiated
```

Looks like the problem was `Server Certificate not found for the key: arn:aws:iam::126623727247:server-certificate/bbl-cert-dfb7b96b-111f-d16e-5854-9936e7153e8b
`

Thanks
Dennis && @jaresty

**Comment by zankich** [comment] 2016-08-22 20:50
@DennisDenuto what commit sha are you running? Did you run the `create-lbs` command when you got the `Server Certificate` error?

**Comment by jaresty** [comment] 2016-08-22 23:05
We don't have the commit sha for that run anymore.  We did run `unsupported-create-lbs`:

```
  bbl \
    --state-dir bbl-infrastructure \
    unsupported-create-lbs \
    --type=cf \
    --cert=/tmp/bbl-cert \
    --key=/tmp/bbl-key \
    --skip-if-exists
```

**Comment by christianang** [comment] 2016-09-06 23:56
Sorry for the delay in the response @jaresty and @DennisDenuto.

From your logs it looks like `bbl` still believes the load balancer is still there, but once it starts the cloudformation update, you can see it recreating the load balancer resources. However, up does not recreate the certificate for the load balancer so it fails.

`bbl` does fast fail if the certificate cannot be found however; so between the time `bbl` started and the time cloudformation got around to attaching the certificate to the load balancer, the certificate was deleted.

So the only way I can see this happening is if you deleted the load balancer and `bbl`'d up at the same time. Which is also unlikely because `bbl` will fast fail if it sees another cloudformation update happening.

Theoretically, you could get `bbl` to pass its fast fail on the certificate existing if you `bbl` up right when `delete-lbs` finishes updating the cloudformation and hasn't deleted the certificate, but that does happen pretty quickly. And hopefully you are not trying to run two bbl commands at the same time.

So far this is the only scenario in which I can see this happening. If you have more information on how you are using bbl we can try to reproduce, otherwise let us know if it happens again.

**Comment by christianang** [comment] 2016-09-07 20:40
As it turns out, this has happened in our CI now, so I was able to gather some more information.

This happened to us on our initial call of `create-lbs` and it was able to create the certificate, but once it got to the cloudformation creation it failed to find the certificate. So it seems to be an issue with aws and cloudformation. Rerunning the command would probably work.

**Comment by christianang** [comment] 2016-09-15 18:58
Closing this issue as it has been a week since the last reply. Feel free to reopen if it happens again.

**Closed by christianang** 2016-09-15 18:58 UTC
Labels: scheduled
