### ISSUE TITLE
bbl destroy fails and is left in a state where subsequent bbl destroys also fail

### ISSUE THREAD

**Issue by ChunyiLyu** [pivotal-cf-experimental/bosh-bootloader#52] opened 2016-08-05 21:16 UTC
We attempted a bbl destroy. However the destroy failed with the following error message: `CloudFormation failure on stack 'bbl-aws-ICU0e'.
Check the AWS console for error events related to this stack,
and/or open a GitHub issue at https://github.com/pivotal-cf-experimental/bosh-bootloader/issues.`

Looking at the cloudformation stack, the following snippet is the root cause of bbl being unable to destroy.

```
12:31:24 UTC-0700	DELETE_FAILED	AWS::CloudFormation::Stack	bbl-aws-ICU0e	The following resource(s) failed to delete: [LoadBalancerSubnet1, VPCGatewayInternetGateway, VPC, VPCGatewayAttachment].
12:31:22 UTC-0700	DELETE_FAILED	AWS::EC2::InternetGateway	VPCGatewayInternetGateway	The internetGateway 'igw-26f9c342' has dependencies and cannot be deleted.
11:51:42 UTC-0700	DELETE_FAILED	AWS::EC2::VPC	VPC	The vpc 'vpc-e11d7f86' has dependencies and cannot be deleted.
11:50:14 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::VPC	VPC	
11:50:11 UTC-0700	DELETE_COMPLETE	AWS::EC2::SecurityGroup	CFRouterSecurityGroup	
11:48:48 UTC-0700	DELETE_COMPLETE	AWS::EC2::Subnet	LoadBalancerSubnet3	
11:48:26 UTC-0700	DELETE_FAILED	AWS::EC2::Subnet	LoadBalancerSubnet1	The subnet 'subnet-70252228' has dependencies and cannot be deleted.
11:48:25 UTC-0700	DELETE_IN_PROGRESS	AWS::EC2::InternetGateway	VPCGatewayInternetGateway	
11:48:23 UTC-0700	DELETE_FAILED	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	Network vpc-e11d7f86 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
```

We ensured that there were no bosh deployments.
Could this be a race condition when deleting the director vm?

Regardless when we attempted to run bbl destroy again, it failed with the following error message:
```
Command 'delete' failed:
  Deleting deployment:
    Checking existance of vm for instance 'unknown/0':
      Checking existance of VM 'i-b26ef94a':
        CPI 'has_vm' method responded with error: CmdError{"type":"Unknown","message":"AWS was not able to validate the provided access credentials","ok_to_retry":false}
```

We think this has left us in a state where the only way to delete the stack is via AWS and not by bbl.

Thanks
@DennisDenuto && Chunyi

**Comment by Amit-PivotalLabs** [comment] 2016-08-07 00:39
Thanks @ChunyiLyu, this is an issue we've seen a few times but not found the root cause.  Do you have the full list of events from the stack deletion?  I'd be curious to see what was deleted in what order, we may need to add some more `DependsOn` keys throughout the CloudFormation template to make sure these things don't happen.  This is definitely not a race with deleting the Director VM.

**Comment by Amit-PivotalLabs** [comment] 2016-08-07 00:41
Relevant: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html#gatewayattachment

**Comment by ChunyiLyu** [comment] 2016-08-08 16:42
Thanks for your reply @Amit-PivotalLabs . Unfortunately we do not have the full list of events after deleting the stack manually ourselves. Sorry about that. We will make sure to save the record if we ran into this problem again.

**Comment by Amit-PivotalLabs** [comment] 2016-08-22 14:51
Going to close this, but please let us know if you see this again @ChunyiLyu, @DennisDenuto.  Events from CloudFormation would be especially helpful if you do indeed hit it again.

**Closed by Amit-PivotalLabs** 2016-08-22 14:51 UTC
Labels: unscheduled
